### ISSUE TITLE
Error 422 for CSP report from Chrome

### ISSUE THREAD

**Issue by Wowhere** [jacobbednarz/go-csp-collector#104]
Error 422 for CSP report from Chrome

1. Open site with CSP where report-to contains link to go-csp-collector using Chrome 126.0.6478.127
2. View request/response through intercepting proxy 

Result: go-csp-collector responds with 422
![изображение](https://github.com/user-attachments/assets/e46ad86c-011c-47b7-8716-8ae28224e627)

go-csp-collector have error in debug log:
"timestamp="2024-08-06T12:02:38+03:00" level=debug message="unable to decode invalid JSON payload: json: cannot unmarshal array into Go value of type handler.CSPReport""

json payload in text file. The same payload works fine with google csp server (csp.withgoogle.com). Seems like go-csp-collector can read only Firefox CSP reports without error
[req_1.txt](https://github.com/user-attachments/files/16508649/req_1.txt)

**Comment by jacobbednarz** [comment]
couple of things here:

1) the `server` here is returning nginx. this tool does not return that header. 
2) having an array of reports suggests this is the reporting API; not CSP (2?). you'll need to use the correct endpoint for the type of reports you are sending.

**Comment by Wowhere** [comment]
1. nginx here as reverse proxy. 
2. tried to send to /reporting-api/csp and it worked well. Seems like it is better to writedown that /reporting-api/csp path is more important as it reads new CSP input, not old as /csp

**Comment by jacobbednarz** [comment]
the differences in which endpoint should be used are covered in the readme under "endpoints". take a read and if you feel there needs to be clarification, please open a PR. 

neither endpoint is more important as they both serve different formats and stages of the CSP standard development. you cannot use them interchangeably.
