### ISSUE TITLE
Allow an array of reports

### ISSUE THREAD

**Issue by landorg** [jacobbednarz/go-csp-collector#67]
I'm getting this when reports are sent from chrome:
```
{"level":"debug","message":"Unable to decode invalid JSON payload: json: cannot unmarshal array into Go value of type main.CSPReport","timestamp":"2022-08-24T11:31:19Z"}
```

I think that chrome is sending multiple reports in an array.
I couldn't find it in the [spec](https://web.dev/reporting-api-migration/) but [this](https://notificare.com/blog/2022/03/18/Monitoring-Content-Security/) says:
> As you can see, the report is part of an array of reports, since there can be multiple types of reports in a single Reporting API call.

**Comment by jacobbednarz** [comment]
thanks for the issue. I'll have to take a look at how we handle this as collection vs single in typed languages isn't an easy process 😅

**Comment by jacobbednarz** [comment]
i have a way forward with this using a custom `Marshal` and `Unmarshal` methods; it's not pretty but it does work.

**Comment by jacobbednarz** [comment]
also, i sat down and looked into this more and these are actually two different (yet similar) things. the first one is a _CSP report_ whereas the second (array of reports) is from the _Reporting API_ for a CSP violation. the latter is the newer, all encompassing collection mechanism so i think i'll keep these separate. i.e. `/csp` can be for the older style reports and `report` (or similar) can be for the reporting API if it is supported by the browser.
