### ISSUE TITLE
arm64 image for go-csp-collector

### ISSUE THREAD

**Issue by Schmitze333** [jacobbednarz/go-csp-collector#90]
First of all thank you for your work on this useful project!

We run `go-csp-collector` in all our public-facing k8s cluster since ages, but we now want to migrate to all-ARM clusters and we miss an image supporting that architecture.

Would it be possible to extend the supported architectures on docker hub?
We would also volunteering to support the necessary actions therefore!

**Comment by jacobbednarz** [comment]
sure! this seems reasonable. i don't personally have any ARM clusters to deploy this on so if you'd like to give it a whirl and report any errors you hit, we can address them in individual PRs. 

i used to have this automatically hooked up to dockerhub with a webhook but since that's now a paid only feature, i'll need to manually push the images once we have them.

**Comment by Schmitze333** [comment]
I fiddled around today and automated a multi arch build via github action.
[see here](https://github.com/Schmitze333/go-csp-collector/blob/multi-arch-builds/.github/workflows/build.yml)

I wonder what your preferred way of working is...
I could imagine that the action is run on a release event and automatically pushes the image to docker hub with the release tag being the image tag. But if you prefer something different just let me know and I'll try to implement it.

**Comment by jacobbednarz** [comment]
that seems fine to me. i've had issues in the past with GitHub Actions and emulating architectures in builds but that was for dependencies so 🤞 this is more straight forward. 

if you want to PR this, i'll drop the credentials in to use and we can get this rolling.

**Comment by Schmitze333** [comment]
Since a multi-arch image is now available from docker hub, I think this issue can be closed.

Thank you @jacobbednarz for handling issue and PR in such a responsive manner! Highly appreciated.
