### ISSUE TITLE
Support source-file

### ISSUE THREAD

**Issue by chennin** [jacobbednarz/go-csp-collector#94]
Please support [source-file](https://csplite.com/csp66/#source-file), and perhaps line-number and column-number as well.

Firefox (at least) sends them, and I would fine the source file URI quite useful in my reports.

**Comment by jacobbednarz** [comment]
this tool largely targets CSP1 since that is the only one that is majority implemented. if you'd like to see support for source-file (or other CSP2 fields), best bet is to send over a PR for review.
